app.py
Removed a redundant call to crawl URL, that caused the crawling process to take double the time.
=> Removed a redundant call to crawl URL

app.py
call should be https instead of http
=> fix request call to https instead of http

AUTHORS.md, app.py
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='instagram.fmaa1-1.fna.fbcdn.net', port=443): Max retries exceeded with url: /t51.2885-15/s640x640/sh0.08/e35/13181475_112346149181392_122674076_n.jpg?ig_cache_key=MTI1MDcwOTcyODM3Njc5NDQxNg%3D%3D.2.l (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb6a989cc>: Failed to establish a new connection: [Errno -2] Name or service not known',))
=> Maximum connection requests error 

AUTHORS.md, app.py
Hey,
I refactored the code a bit. I replaced the recursive crawl and get_media with a generator that yields an stream of media files so that crawl doesn't need to handle pagination. This way functions have a little less responsibilities.
I also moved the 'futures waiting' and 'progress bar' functionality to scrape method. I think it's better if class internals are not exposed.
If you like it, merge it, otherwise forget about it. I was just having some fun. :)
=> Some code refactoring

AUTHORS.md, instagram_scraper/app.py
Pretty straightforward - hopefully this is useful to someone else!
=> Flag for preserving username subdirectory when -d flag is set.

AUTHORS.md, README.md, instagram_scraper/app.py
Use the flag --filter can search for specific tags with in a user's post
=> added tag filter within user's media

AUTHORS.md, instagram_scraper/app.py
Getting the hang of project structure. Here's a small fix that someone was asking for.
=> Fixed the --filter feature

instagram_scraper/app.py
1) Add a split for the username file to allow # to be a comment
character.
2) If a user was not found, a valueError exception was being created.
The higher level code was not catching it, and causing the app to
crash.  Added Try/Catch to consume the error and output a warning.
=> Allow # for Comment in username file.  Add Try/Catch to catch ValueError if user not found.

instagram_scraper/app.py
The discovered high resolution profile picture url wasn't used to define a download task
=> The bug in get_profile_pic

instagram_scraper/app.py
This method fix the problem that other user say in #230 #231
=> Fix Login Csrftoken #233 #231

instagram_scraper/app.py
I've fixed a bug introduced by recent changes and also included a login fix from #234, I don't know if it fix anything, I can't reproduce the bug #233. But if it fixes #233 then this pull request should also fix #238
=>  The bug in url parsing causes failure on url with query

instagram_scraper/app.py
Use the cookie _'sessionid'_ from login for fetching the stories and renew it by the response-cookie, cause it seems to be rotated.
Got a bit deeper in the code and the way instagram handles the requests. The point is that the _'sessionid'_ is not present anymore after calling the method `get_shared_data()`, causes by fetching information from the api (`USER_INFO = 'https://i.instagram.com/api/v1/users/{0}/info/'`) and this get-request does not provide the response-cookie _'sessionid'_. 
I think this a much better way, far not the best, but better than the previous quick-fix #275 #276 
How about this solution?
=> Fetching stories fix #2

instagram_scraper/app.py
https://github.com/rarcega/instagram-scraper/issues/339
=> Scrap profile metadata

AUTHORS.md, README.md, instagram_scraper/app.py
Allow to use proxy while using instagram session.
=> Configure proxy

instagram_scraper/app.py
This bug was introduced with this PR #327.
=> Get profile info if user is logged in.

instagram_scraper/app.py
https://github.com/rarcega/instagram-scraper/issues/353
=> Fix bug when using --latest parameter.

instagram_scraper/app.py
=> Fix python3 problem

instagram_scraper/app.py
This is very useful for users that are using the app programmatically as a package for other projects.
=> Added ability to specify a custom logger 

instagram_scraper/app.py
A quick fix for #424 and python3 compatibility issue
=> A quick fix for #424

instagram_scraper/app.py
Fix issue https://github.com/rarcega/instagram-scraper/issues/449
=> Get profile metadata without login.

AUTHORS.md, instagram_scraper/app.py, instagram_scraper/constants.py
Fix issues #147 #261 #291 #323
=> Fetch highlight stories.

instagram_scraper/app.py
=> Workaround for issue #488

instagram_scraper/app.py, instagram_scraper/constants.py, setup.py
=> Get live video / broadcast

instagram_scraper/app.py
handing missing has_anonymous_profile_picture key from response
=> add exception handing

AUTHORS.md, instagram_scraper/app.py
If the json result has has_anonymous_profile_picture key, check the value
If the value is False then try to get user profile picture
=> Try to get profile picture

instagram_scraper/app.py
=> video_resources fix for #594

.travis.yml, instagram_scraper/app.py, setup.py
Broadcast feature is obsolete, they are saved in IGTV.
=> Remove obsolete broadcasts

.dockerignore, .gitignore, Dockerfile, README.md, docker_entrypoint.sh
Support for Docker
Will be work only after merging https://github.com/arc298/instagram-scraper/pull/659
=> Docker feature

AUTHORS.md, instagram_scraper/app.py
Add business name, phone number, category and external url to profile_info
=> Business info

instagram_scraper/app.py
=> Add exit code to authentication failure

instagram_scraper/app.py
Reverts arc298/instagram-scraper#511
=> Revert "Fall back to alternate content-length header"

instagram_scraper/app.py
Debug info for JSON loads function.
Possible fixes #108 #482 #626 #628 #648 #662 #675 #707 #705 #710 #711 #717
=> Possibility to determine JSON loading error.

instagram_scraper/app.py
Implement suggestion by @VasiliPupkin256 in https://github.com/arc298/instagram-scraper/pull/760#issuecomment-1018050569 in case IG does something weird.
--
`scrape` function warns the user if a profile he's trying to scrap is private. For unknown reason it does some extra checks rather than simply test the value of `is_private`. This produces wrong results in some cases:
- you can have a private profile that has zero posts - it doesn't matter since it may have stories that you can't access
- recently IG added a feature that a post can have multiple authors. In this case you can still scrape posts that are co-authored by the private profile if the other one is public
--
When scraping to a VirtualBox shared folder, I often experience a bug where the `download` function would throw `[Errno …
=> Fix file download, properly show if profile is private

instagram_scraper/app.py
Fix absolute and relative paths for --followings-output
=> Fix --followings-output path

instagram_scraper/app.py
Added fileno method for LockedStream to avoid exceptions like `AttributeError: 'LockedStream' object has no attribute 'fileno'`
=> Add fileno method for class LockedStream
